modLoader="javafml"
loaderVersion="[39,)"
license="GNU General Public License, Version 3 (GPLv3)"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="craftingtableplus"
version="1.18.1-1.0"
displayName="Crafting Table Plus"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://allmods.alhazera25.my.id/mods/crafting-table-plus"
logoFile="ctp.png"
#credits=""
authors="Albania Hazera"
description='''
Thanks for download and using our mod
'''

[[dependencies.craftingtableplus]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.craftingtableplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
